spring:
  datasource:
    url: jdbc:mysql://localhost:3306/comment-db
    username: root
    password: Test@810
    jpa:
      hibernate:
        ddl-auto: update
        show-sql: true
        properties:
          hibernate:
            dialect: org.hibernate.dialect.MySQL8Dialect
            server:
              port: 8082
